# Generated by Django 5.1.4 on 2025-01-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_category_options_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_body',
            new_name='comment',
        ),
    ]
