# Generated by Django 5.1.4 on 2025-01-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_rename_comment_body_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=225)),
                ('phone', models.CharField(max_length=11)),
                ('message', models.TextField(max_length=3000)),
            ],
        ),
    ]
