# Generated by Django 5.1.4 on 2025-01-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUs',
        ),
    ]
