# Generated by Django 5.1.4 on 2025-01-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_rename_contact_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('subscribed', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'ContactUs'},
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
