# Generated by Django 5.1.4 on 2025-03-29 00:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_newsletter_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Blog_images'),
        ),
    ]
